database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  # user: iyufcqrl
  user: njkksidt

  # the password
  # password: 2iy0Ltc80KUSr6woE9OE8hW40AG_hUv8
  password: CLB8kygGhAnfM2VpLxSuKNGDmxLoG7zy

  # the JDBC URL
  # url: jdbc:postgres://iyufcqrl:2iy0Ltc80KUSr6woE9OE8hW40AG_hUv8@echo.db.elephantsql.com:5432/iyufcqrl
  url: jdbc:postgres://njkksidt:CLB8kygGhAnfM2VpLxSuKNGDmxLoG7zy@echo.db.elephantsql.com:5432/njkksidt

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 50s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  
server:
  applicationConnectors:
  - type: http 
    port: 8100
