database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: iyufcqrl

  # the password
  password: 2iy0Ltc80KUSr6woE9OE8hW40AG_hUv8

  # the JDBC URL
  url: jdbc:postgresql://echo.db.elephantsql.com:5432/iyufcqrl

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 2
  initialSize: 2
  # the maximum number of connections to keep open
  maxSize: 5

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  
server:
  maxThreads: 110
  minThreads: 8
  applicationConnectors:
  - type: http 
    port: 8100
    acceptorThreads: 50
    selectorThreads: 50
